INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('PI_CORRENTES',-10.45194435,-45.13639069); 
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('RS_SALGADOFILHO',-29.9942,-51.1714); 
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('SP_CONGONHAS',-23.6267,-46.6553);
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('SP_GUARULHOS',-23.4322,-46.4692); 
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('PE_GUARARAPES',-8.0735,-34.5522); 
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('AM_EDUARDOGOMES',-3.03861,-60.0497); 
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('AC_RIOBRANCO',-9.5208,-67.5253);
INSERT INTO aeroporto(nome, latitude, longitude) VALUES ('RJ_GALEAO',-22.8089,-43.2436);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/RS_SALGADOFILHO', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/SP_CONGONHAS', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/SP_GUARULHOS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/PE_GUARARAPES', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/AM_EDUARDOGOMES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PI_CORRENTES/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/SP_CONGONHAS', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/SP_GUARULHOS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/PE_GUARARAPES', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/AM_EDUARDOGOMES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RS_SALGADOFILHO/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/SP_GUARULHOS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/PE_GUARARAPES', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/AM_EDUARDOGOMES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_CONGONHAS/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/SP_CONGONHAS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/PE_GUARARAPES', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/AM_EDUARDOGOMES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('SP_GUARULHOS/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/SP_CONGONHAS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/SP_GUARULHOS', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/AM_EDUARDOGOMES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('PE_GUARARAPES/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/SP_CONGONHAS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/SP_GUARULHOS', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/PE_GUARARAPES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/AC_RIOBRANCO', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AM_EDUARDOGOMES/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/SP_CONGONHAS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/SP_GUARULHOS', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/PE_GUARARAPES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/AM_EDUARDOGOMES', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('AC_RIOBRANCO/RJ_GALEAO', 600, 6, 4);

Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/PI_CORRENTES', 1,2,800);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/RS_SALGADOFILHO', 800, 2, 1);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/SP_CONGONHAS', 500, 3, 4);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/SP_GUARULHOS', 200, 4, 5);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/PE_GUARARAPES', 650, 5, 3);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/AM_EDUARDOGOMES', 300, 1, 6);
Insert into aerovia(nome, id_origem, id_destino, distancia) VALUES ('RJ_GALEAO/AC_RIOBRANCO', 600, 6, 4);

Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE11',1,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE22',1,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE33',1,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE44',1,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE55',1,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE66',1,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE77',1,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE88',2,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE99',2,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE101',2,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE200',2,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE300',2,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE466',2,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE524',2,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE569',3,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE754',3,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE854',3,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE846',3,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE784',3,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE45',3,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE102',3,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE104',4,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE404',4,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE504',4,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE120',4,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE121',4,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE171',4,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE333',4,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE999',5,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE555',5,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE400',5,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE600',5,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE1010',5,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE2020',5,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE3030',5,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE4040',6,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE5050',6,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE6060',6,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE7070',6,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE8080',6,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE9090',6,7);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE720',6,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE721',7,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE722',7,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE723',7,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE724',7,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE725',7,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE726',7,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE727',7,8);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE728',8,1);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE111',8,2);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE02',8,3);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE01',8,4);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE03',8,5);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE05',8,6);
Insert into rota(nome, id_origem, id_destino) VALUES ('ROUTE09',8,7);

Insert into rota_aerovia(id_rota, id_aerovia) VALUES (1, 1);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (2, 2);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (3, 3);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (4, 4);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (5, 5);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (6, 6);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (6, 7);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (7, 8);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (7, 9);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (8, 10);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (8, 11);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (9, 12);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (9, 13);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (10, 14);
Insert into rota_aerovia(id_rota, id_aerovia) VALUES (10, 15);

Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-01', 1, 25000, 1);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-01', 1, 25000, 2);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-02', 1, 25000, 3);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-03', 1, 25000, 4);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-04', 1, 25000, 5);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-05', 1, 25000, 6);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-06', 1, 25000, 7);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-06', 1, 25000, 8);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-07', 1, 25000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-08', 1, 25000, 19);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-09', 1, 25000, 20);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-10', 1, 25000, 21);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-11', 1, 26000, 10);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-12', 1, 26000, 5);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-13', 1, 26000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-14', 1, 27000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-15', 1, 28000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-16', 1, 33000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-17', 1, 34000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-18', 10, 30000, 12);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-19', 11, 30000, 12);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-20', 11, 30000, 13);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-21', 10, 30000, 14);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-22', 11, 30000, 14);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-23', 10, 30000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-24', 11, 30000, 18);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-25', 10, 30000, 22);
Insert into ocupacao_aerovia(data, id_aerovia, altitude_slot, horario_slot) VALUES ('2023-05-26', 11, 30000, 22);

Insert into planodevoo(id_rota, data, horariopartida, altitude, vel_cruzeiro) VALUES (1,'2023-05-19',18,34000,800);
Insert into planodevoo(id_rota, data, horariopartida, altitude, vel_cruzeiro) VALUES (2,'2023-05-19',18,34000,800);
Insert into planodevoo(id_rota, data, horariopartida, altitude, vel_cruzeiro) VALUES (3,'2023-05-01',1,25000,700);
Insert into planodevoo(id_rota, data, horariopartida, altitude, vel_cruzeiro) VALUES (4,'2023-05-01',7,25000,900);
Insert into planodevoo(id_rota, data, horariopartida, altitude, vel_cruzeiro) VALUES (5,'2023-05-02',9,25000,600);

COMMIT WORK;